# 12.2 array 패키지 사용하기

In [4]:
import array
a = array.array('h', [1, 2, 3])
a

array('h', [1, 2, 3])

In [7]:
a = array.array('h', range(1000))

In [8]:
a = array.array('l', range(1_000_000))

# 12.4 numpy 소개: 1부터 100만까지 더하기

In [9]:
import numpy as np

In [10]:
a_list = list(range(1, 1_000_001))
print(sum(a_list))

500000500000


In [11]:
import numpy as np

a = np.arange(1, 1_000_001, dtype=np.int64)
print(sum(a))

500000500000


In [12]:
import numpy as np
from time import time

def bench_marks(n):
    t1 = time()
    
    a_list = list(range(1, n + 1))
    tot = sum(a_list)
    
    t2 = time()
    print('Time taken by Python is', t2 - t1)
    t1 = time()
    
    a = np.arange(1, n + 1)
    tot = np.sum(a)
    
    t2 = time()
    print('Time taken by numpy is', t2 - t1)
    
bench_marks(10_000_000)    

Time taken by Python is 0.6095268726348877
Time taken by numpy is 0.03201007843017578


# 12.5 numpy 배열 만들기

```python
a = np.arange(1, n + 1)  # 1부터 n까지 범위의 numpy 배열 생성
```

```python
import numpy as np

np.int8   # dtype처럼 사용
'int8'    # 이 또한 dtype처럼 사용
```

## 12.5.1 array 함수(array로 변환)

In [14]:
import numpy as np
a = np.array([1, 2, 3])

In [15]:
a = np.array([[1, 2, 3], [10, 20, 30], [0, 0, -1]])
print(a)

[[ 1  2  3]
 [10 20 30]
 [ 0  0 -1]]


In [17]:
import numpy as np
a = np.array([[1, 2, 3], [10, 20, 300]])
a

array([[  1,   2,   3],
       [ 10,  20, 300]])

In [18]:
a = np.array([[1, 2, 3], [10, 20, 300, 4]])
a

array([list([1, 2, 3]), list([10, 20, 300, 4])], dtype=object)

## 12.5.2 arange 함수

In [19]:
import numpy as np
a = np.arange(1, 1000001)  # 100만 개의 항목으로 구성된 배열 생성

## 12.5.3 linspace 함수

In [20]:
import numpy as np
a = np.linspace(0, 1.0, num=5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
a = np.linspace(0, 1.0, num=6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [22]:
np.linspace(1, 5, num=5, dtype=np.int16)

array([1, 2, 3, 4, 5], dtype=int16)

# 12.5.4 empty 함수

In [2]:
import numpy as np
a = np.empty((2, 2), dtype='int16')
a

array([[0, 0],
       [0, 0]], dtype=int16)

In [4]:
a = np.empty((3, 2), dtype='float32')
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

## 12.5.5 eye 함수

In [5]:
a = np.eye(4, dtype='int')
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [6]:
a = np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## 12.5.6 ones 함수

In [7]:
import numpy as np
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a = np.ones((2, 2, 3), dtype=np.int16)
a

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [10]:
a = np.ones(6, dtype=np.bool)
a

array([ True,  True,  True,  True,  True,  True])

## 12.5.7 zeros 함수

In [11]:
import numpy as np
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
a = np.zeros((2, 2, 3), dtype=np.int16)
a

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [14]:
a = np.zeros(5, dtype=np.bool)
a

array([False, False, False, False, False])

## 12.5.8 full 함수

In [15]:
import numpy as np
a = np.full((2, 2), 3.14)
a

array([[3.14, 3.14],
       [3.14, 3.14]])

In [17]:
a = np.full(8, 100)
a

array([100, 100, 100, 100, 100, 100, 100, 100])

In [18]:
a = np.full(5, 'ken')
a

array(['ken', 'ken', 'ken', 'ken', 'ken'], dtype='<U3')

In [19]:
a[0] = 'tommy'  # 가능하지만 잘려나간다.
a

array(['tom', 'ken', 'ken', 'ken', 'ken'], dtype='<U3')

## 12.5.9 copy 함수

```python
import numpy as np
b_arr = np.copy(a_arr)   # a_arr 배열의 값을 b_arr로 완전히 복사
```

# 12.5.10 fromfunction 함수

In [20]:
import numpy as np

def simple(n):
    return n + 1

a = np.fromfunction(simple, (5,), dtype='int32')
a

array([1, 2, 3, 4, 5])

In [21]:
a = np.fromfunction(lambda n:n+1, (5,), dtype='int32')

In [22]:
def add_it(r, c):
    return r + c

a = np.fromfunction(add_it, (3, 3), dtype='int32')
a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [23]:
a = np.fromfunction(lambda r, c: 1, (3, 3), dtype='int')
a

1

# 12.6 예시: 곱셈표 만들기

In [24]:
import numpy as np

def multy(r, c):
    return (r + 1) * (c + 1)

a = np.fromfunction(multy, (10, 10), dtype=np.int16)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]], dtype=int16)

In [26]:
a = np.fromfunction(lambda r, c: (r+1) * (c+1), (10, 10), dtype=np.int16)

In [27]:
s = str(a)
s = s.replace('[', '')
s = s.replace(']', '')
s = ' ' + s
print(s)

   1   2   3   4   5   6   7   8   9  10
   2   4   6   8  10  12  14  16  18  20
   3   6   9  12  15  18  21  24  27  30
   4   8  12  16  20  24  28  32  36  40
   5  10  15  20  25  30  35  40  45  50
   6  12  18  24  30  36  42  48  54  60
   7  14  21  28  35  42  49  56  63  70
   8  16  24  32  40  48  56  64  72  80
   9  18  27  36  45  54  63  72  81  90
  10  20  30  40  50  60  70  80  90 100


# 12.7 numpy 배열의 배치 연산

In [1]:
import numpy as np

A = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [2]:
A = np.arange(16).reshape((4, 4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [3]:
A = np.fromfunction(lambda r, c: r*4 + c, (4, 4))
print(A)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [4]:
B = np.eye(4, dtype='int16')
print(B)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [5]:
C = A * 10
print(C)

[[  0.  10.  20.  30.]
 [ 40.  50.  60.  70.]
 [ 80.  90. 100. 110.]
 [120. 130. 140. 150.]]


In [6]:
C = A * A
print(C)

[[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]
 [144. 169. 196. 225.]]


In [7]:
print(C.reshape((2, 8)))

[[  0.   1.   4.   9.  16.  25.  36.  49.]
 [ 64.  81. 100. 121. 144. 169. 196. 225.]]


In [8]:
A *= A
print(A)

[[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]
 [144. 169. 196. 225.]]


In [9]:
C = A * B
print(C)

[[  0.   0.   0.   0.]
 [  0.  25.   0.   0.]
 [  0.   0. 100.   0.]
 [  0.   0.   0. 225.]]


# 12.8 numpy 슬라이스 정렬하기

In [11]:
A = np.arange(1, 11)
print(A)
print(A[2:5])

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5]


In [12]:
A[2:5] = 0
print(A)

[ 1  2  0  0  0  6  7  8  9 10]


In [14]:
A = np.arange(1, 11)
A[2:5] += 100
print(A)

[  1   2 103 104 105   6   7   8   9  10]


In [16]:
A = np.arange(1, 11)
A[2:5] *= [100, 200, 300]
print(A)

[   1    2  300  800 1500    6    7    8    9   10]


In [17]:
A = np.arange(51)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [18]:
A[1] = 0
A[2 * 2::2] = 0
print(A)

[ 0  0  2  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0 21  0 23
  0 25  0 27  0 29  0 31  0 33  0 35  0 37  0 39  0 41  0 43  0 45  0 47
  0 49  0]


In [19]:
A[3* 3::3] = 0
print(A)

[ 0  0  2  3  0  5  0  7  0  0  0 11  0 13  0  0  0 17  0 19  0  0  0 23
  0 25  0  0  0 29  0 31  0  0  0 35  0 37  0  0  0 41  0 43  0  0  0 47
  0 49  0]


In [20]:
# my_prime_list = [i for i in A if i > 0]
P = A[A > 0]
print(P)

[ 2  3  5  7 11 13 17 19 23 25 29 31 35 37 41 43 47 49]


# 12.9 다차원 슬라이싱

In [21]:
A = np.arange(1, 17).reshape((4, 4))
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
print(A[1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
A[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [24]:
G = np.zeros((6, 6))
G[1:4, 2] = 1
print(G)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
print(G[1:4, 1:4])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [26]:
neighbor_count = np.sum(G[1:4, 1:4]) - G[2, 2]
print(neighbor_count)

2.0


# 12.10 불리언 배열: numpy에 마스킹하기!

In [28]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
B1 = B > 4
print(B1)

[[False False False]
 [False  True  True]
 [ True  True  True]]


In [30]:
print(B * (B > 4))

[[0 0 0]
 [0 5 6]
 [7 8 9]]


In [31]:
print(B[B > 7])

[8 9]


In [32]:
print(B[B % 3 == 1])

[1 4 7]


In [35]:
B2  = (B > 2) & (B < 7) # AND 연산
print(B2)

[[False False  True]
 [ True  True  True]
 [False False False]]


In [36]:
print(B[B2])

[3 4 5 6]


In [37]:
print(B[(B == 1) | (B > 6)])  # 'OR' 연산자

[1 7 8 9]


# 12.11 numpy와 에라토스테네스의 채

In [41]:
import time

def seive(n):
    t1 = time.time() * 1000
    b_list = [True] * (n + 1)
    for i in range(2, n+1):
        if b_list[i]:
            for j in range(i*i, n+1, i):
                b_list[j] = False
    primes = [i for i in range(2, n+1) if b_list[i]]
    t2 = time.time() * 1000
    print('sieve took', t2-t1, 'milliseconds.')

In [42]:
import numpy as np
import time

def np_seive(n):
    t1 = time.time() * 1000
    # B 생성, 모든 항목을 True로 설정한다.
    B = np.ones(n + 1, dtype=np.bool)
    B[0:2] = False
    for i in range(2, n + 1):
        if B[i]:
            B[i*i: n+1: i] = False
    P = np.arange(n+1)[B]
    t2 = time.time() * 1000
    print('np_sieve took', t2-t1, 'milliseconds.')

In [45]:
seive(5000)
np_seive(5000)

np_sieve took 1.000732421875 milliseconds.
np_sieve took 1.9990234375 milliseconds.


In [46]:
seive(50000)
np_seive(50000)

np_sieve took 29.0166015625 milliseconds.
np_sieve took 11.97509765625 milliseconds.


# 12.12 numpy 통계 구하기: 표준편차

In [1]:
import numpy as np
import numpy.random as ran
A = ran.rand(10)
A

array([0.09181736, 0.90783952, 0.87069995, 0.43668284, 0.39676951,
       0.51279682, 0.68951292, 0.94345457, 0.12388615, 0.22508391])

In [2]:
A = ran.random(100000)
np.mean(A)

0.5005747345009774

In [3]:
np.sum(A)

50057.47345009774

In [4]:
np.median(A)

0.5008599901525899

In [5]:
np.std(A)

0.2887552821847982

In [10]:
A2 = (A - np.mean(A)) ** 2
result = (np.mean(A2)) ** 0.5
result

0.2887552821847982

In [11]:
np.std(A)

0.2887552821847982

In [15]:
import numpy as np
import time
import numpy.random as ran

def get_std1(ls):
    t1 = time.time()
    m = sum(ls)/len(ls)
    ls2 = [(i - m) ** 2 for i in ls]
    sd = (sum(ls2)/len(ls2)) ** .5
    t2 = time.time()
    print('Python took', t2-t1)
    
def get_std2(A):
    t1 = time.time()
    A2 = (A - np.mean(A)) ** 2
    result = (np.mean(A2)) ** .5
    t2 = time.time()
    print('Numpy took',t2-t1)
    
def get_std3(A):
    t1 = time.time()
    result = np.std(A)
    t2 = time.time()
    print('np.std took', t2-t1)
    
A = ran.rand(1000000)
get_std1(A)
get_std2(A)
get_std3(A)

Python took 0.8980534076690674
Numpy took 0.015618324279785156
np.std took 0.0


# 12.13 numpy 행과 열 가져오기

In [16]:
import numpy as np
import numpy.random as ran

A = ran.randint(1, 20, (3, 4))
print(A)

[[ 9 12 19  6]
 [16 12 16 14]
 [ 1  9 18  2]]


In [17]:
np.mean(A)

11.166666666666666

In [18]:
np.sum(A)

134

In [19]:
np.std(A)

5.6837976349933115

In [22]:
np.sum(A, axis=0)

array([26, 33, 53, 22])

In [23]:
np.sum(A, axis=1)

array([46, 58, 30])

In [25]:
B = np.fromfunction(lambda r, c: c, (4, 5), dtype=np.int32)
B

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [26]:
np.sum(B, axis=0)

array([ 0,  4,  8, 12, 16])

In [27]:
np.sum(B, axis=1)

array([10, 10, 10, 10])

In [30]:
B = np.fromfunction(lambda r, c: c, (4, 5), dtype=np.int32)
B_rows = np.sum(B, axis=1)
B_rows

array([10, 10, 10, 10])

In [31]:
B1 = np.c_[B, B_rows]
B1

array([[ 0,  1,  2,  3,  4, 10],
       [ 0,  1,  2,  3,  4, 10],
       [ 0,  1,  2,  3,  4, 10],
       [ 0,  1,  2,  3,  4, 10]])

In [33]:
B_cols = np.sum(B1, axis=0)
B_cols

array([ 0,  4,  8, 12, 16, 40])

In [35]:
B2 = np.r_[B1, [B_cols]]
B2

array([[ 0,  1,  2,  3,  4, 10],
       [ 0,  1,  2,  3,  4, 10],
       [ 0,  1,  2,  3,  4, 10],
       [ 0,  1,  2,  3,  4, 10],
       [ 0,  4,  8, 12, 16, 40]])

In [37]:
def spreadsheet(A):
    AC = np.sum(A, axis=1)
    A2 = np.c_[A, AC]
    AR = np.sum(A2, axis=0)
    return np.r_[A2, [AR]]

arr = np.arange(15).reshape(3, 5)
print(arr)
print(spreadsheet(arr))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[  0   1   2   3   4  10]
 [  5   6   7   8   9  35]
 [ 10  11  12  13  14  60]
 [ 15  18  21  24  27 105]]
