# 12.2 array 패키지 사용하기

In [4]:
import array
a = array.array('h', [1, 2, 3])
a

array('h', [1, 2, 3])

In [7]:
a = array.array('h', range(1000))

In [8]:
a = array.array('l', range(1_000_000))

# 12.4 numpy 소개: 1부터 100만까지 더하기

In [9]:
import numpy as np

In [10]:
a_list = list(range(1, 1_000_001))
print(sum(a_list))

500000500000


In [11]:
import numpy as np

a = np.arange(1, 1_000_001, dtype=np.int64)
print(sum(a))

500000500000


In [12]:
import numpy as np
from time import time

def bench_marks(n):
    t1 = time()
    
    a_list = list(range(1, n + 1))
    tot = sum(a_list)
    
    t2 = time()
    print('Time taken by Python is', t2 - t1)
    t1 = time()
    
    a = np.arange(1, n + 1)
    tot = np.sum(a)
    
    t2 = time()
    print('Time taken by numpy is', t2 - t1)
    
bench_marks(10_000_000)    

Time taken by Python is 0.6095268726348877
Time taken by numpy is 0.03201007843017578


# 12.5 numpy 배열 만들기

```python
a = np.arange(1, n + 1)  # 1부터 n까지 범위의 numpy 배열 생성
```

```python
import numpy as np

np.int8   # dtype처럼 사용
'int8'    # 이 또한 dtype처럼 사용
```

## 12.5.1 array 함수(array로 변환)

In [14]:
import numpy as np
a = np.array([1, 2, 3])

In [15]:
a = np.array([[1, 2, 3], [10, 20, 30], [0, 0, -1]])
print(a)

[[ 1  2  3]
 [10 20 30]
 [ 0  0 -1]]


In [17]:
import numpy as np
a = np.array([[1, 2, 3], [10, 20, 300]])
a

array([[  1,   2,   3],
       [ 10,  20, 300]])

In [18]:
a = np.array([[1, 2, 3], [10, 20, 300, 4]])
a

array([list([1, 2, 3]), list([10, 20, 300, 4])], dtype=object)

## 12.5.2 arange 함수

In [19]:
import numpy as np
a = np.arange(1, 1000001)  # 100만 개의 항목으로 구성된 배열 생성

## 12.5.3 linspace 함수

In [20]:
import numpy as np
a = np.linspace(0, 1.0, num=5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
a = np.linspace(0, 1.0, num=6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [22]:
np.linspace(1, 5, num=5, dtype=np.int16)

array([1, 2, 3, 4, 5], dtype=int16)