# 12.2 array 패키지 사용하기

In [4]:
import array
a = array.array('h', [1, 2, 3])
a

array('h', [1, 2, 3])

In [7]:
a = array.array('h', range(1000))

In [8]:
a = array.array('l', range(1_000_000))

# 12.4 numpy 소개: 1부터 100만까지 더하기

In [9]:
import numpy as np

In [10]:
a_list = list(range(1, 1_000_001))
print(sum(a_list))

500000500000


In [11]:
import numpy as np

a = np.arange(1, 1_000_001, dtype=np.int64)
print(sum(a))

500000500000


In [12]:
import numpy as np
from time import time

def bench_marks(n):
    t1 = time()
    
    a_list = list(range(1, n + 1))
    tot = sum(a_list)
    
    t2 = time()
    print('Time taken by Python is', t2 - t1)
    t1 = time()
    
    a = np.arange(1, n + 1)
    tot = np.sum(a)
    
    t2 = time()
    print('Time taken by numpy is', t2 - t1)
    
bench_marks(10_000_000)    

Time taken by Python is 0.6095268726348877
Time taken by numpy is 0.03201007843017578


# 12.5 numpy 배열 만들기

```python
a = np.arange(1, n + 1)  # 1부터 n까지 범위의 numpy 배열 생성
```

```python
import numpy as np

np.int8   # dtype처럼 사용
'int8'    # 이 또한 dtype처럼 사용
```

## 12.5.1 array 함수(array로 변환)

In [14]:
import numpy as np
a = np.array([1, 2, 3])

In [15]:
a = np.array([[1, 2, 3], [10, 20, 30], [0, 0, -1]])
print(a)

[[ 1  2  3]
 [10 20 30]
 [ 0  0 -1]]


In [17]:
import numpy as np
a = np.array([[1, 2, 3], [10, 20, 300]])
a

array([[  1,   2,   3],
       [ 10,  20, 300]])

In [18]:
a = np.array([[1, 2, 3], [10, 20, 300, 4]])
a

array([list([1, 2, 3]), list([10, 20, 300, 4])], dtype=object)

## 12.5.2 arange 함수

In [19]:
import numpy as np
a = np.arange(1, 1000001)  # 100만 개의 항목으로 구성된 배열 생성

## 12.5.3 linspace 함수

In [20]:
import numpy as np
a = np.linspace(0, 1.0, num=5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
a = np.linspace(0, 1.0, num=6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [22]:
np.linspace(1, 5, num=5, dtype=np.int16)

array([1, 2, 3, 4, 5], dtype=int16)

# 12.5.4 empty 함수

In [2]:
import numpy as np
a = np.empty((2, 2), dtype='int16')
a

array([[0, 0],
       [0, 0]], dtype=int16)

In [4]:
a = np.empty((3, 2), dtype='float32')
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

## 12.5.5 eye 함수

In [5]:
a = np.eye(4, dtype='int')
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [6]:
a = np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## 12.5.6 ones 함수

In [7]:
import numpy as np
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a = np.ones((2, 2, 3), dtype=np.int16)
a

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [10]:
a = np.ones(6, dtype=np.bool)
a

array([ True,  True,  True,  True,  True,  True])

## 12.5.7 zeros 함수

In [11]:
import numpy as np
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
a = np.zeros((2, 2, 3), dtype=np.int16)
a

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [14]:
a = np.zeros(5, dtype=np.bool)
a

array([False, False, False, False, False])

## 12.5.8 full 함수

In [15]:
import numpy as np
a = np.full((2, 2), 3.14)
a

array([[3.14, 3.14],
       [3.14, 3.14]])

In [17]:
a = np.full(8, 100)
a

array([100, 100, 100, 100, 100, 100, 100, 100])

In [18]:
a = np.full(5, 'ken')
a

array(['ken', 'ken', 'ken', 'ken', 'ken'], dtype='<U3')

In [19]:
a[0] = 'tommy'  # 가능하지만 잘려나간다.
a

array(['tom', 'ken', 'ken', 'ken', 'ken'], dtype='<U3')

## 12.5.9 copy 함수

```python
import numpy as np
b_arr = np.copy(a_arr)   # a_arr 배열의 값을 b_arr로 완전히 복사
```

# 12.5.10 fromfunction 함수

In [20]:
import numpy as np

def simple(n):
    return n + 1

a = np.fromfunction(simple, (5,), dtype='int32')
a

array([1, 2, 3, 4, 5])

In [21]:
a = np.fromfunction(lambda n:n+1, (5,), dtype='int32')

In [22]:
def add_it(r, c):
    return r + c

a = np.fromfunction(add_it, (3, 3), dtype='int32')
a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [23]:
a = np.fromfunction(lambda r, c: 1, (3, 3), dtype='int')
a

1

# 12.6 예시: 곱셈표 만들기

In [24]:
import numpy as np

def multy(r, c):
    return (r + 1) * (c + 1)

a = np.fromfunction(multy, (10, 10), dtype=np.int16)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]], dtype=int16)

In [26]:
a = np.fromfunction(lambda r, c: (r+1) * (c+1), (10, 10), dtype=np.int16)

In [27]:
s = str(a)
s = s.replace('[', '')
s = s.replace(']', '')
s = ' ' + s
print(s)

   1   2   3   4   5   6   7   8   9  10
   2   4   6   8  10  12  14  16  18  20
   3   6   9  12  15  18  21  24  27  30
   4   8  12  16  20  24  28  32  36  40
   5  10  15  20  25  30  35  40  45  50
   6  12  18  24  30  36  42  48  54  60
   7  14  21  28  35  42  49  56  63  70
   8  16  24  32  40  48  56  64  72  80
   9  18  27  36  45  54  63  72  81  90
  10  20  30  40  50  60  70  80  90 100
